__title__ = 'Flask-Static-Compress'
__description__ = 'Auto-detects your static files for minification, combination, and versioning. Like Django-Compressor for Flask.'
__url__ = 'https://github.com/alanhamlett/flask-static-compress'
__version_info__ = ('1', '0', '3')
__version__ = '.'.join(__version_info__)
__author__ = 'Alan Hamlett'
__author_email__ = 'alan.hamlett@gmail.com'
__license__ = 'BSD'
__copyright__ = 'Copyright 2016 Alan Hamlett'
